### ISSUE TITLE
Logging in loads blanks actions screen

### ISSUE THREAD

**Issue by richardreitzenstein** [mostlyserious/craft-promptly#1]
Love the potential of the plugin! However on any project I install it on, when I log back into the CMS it will jump straight to /admin/actions/promptly/prompts, showing an almost blank screen at with just two square brackets displaying ([]).

Manually going back to /admin works fine but that's a bit too much to tell a client so had to disable the plugin for now.

I've tried adding a promptly.php file to see if that made a difference but no fix unfortunately.

**Comment by corneliusio** [comment]
@richardreitzenstein Yes! I discovered this issue pop up a couple days ago and have a fix queued up. Will be aiming to get it released tomorrow. And thanks, we're also excited for what is possible here.

**Comment by corneliusio** [comment]
@richardreitzenstein This redirect bug has been fixed in 1.1.0. You should be good to pull in the most recent release to fix. (Sorry for delay, have been sick and wasn't in the office yesterday)

**Comment by richardreitzenstein** [comment]
All good, thanks heaps I will give it a shot :)Sent from my iPhoneOn 19 Jul 2023, at 12:06 am, Cornelius Ukena ***@***.***> wrote:﻿
@richardreitzenstein This redirect bug has been fixed in 1.1.0. You should be good to pull in the most recent release to fix. (Sorry for delay, have been sick and wasn't in the office yesterday)

**Comment by richardreitzenstein** [comment]
Can confirm it's working for me now, thank you!
